# Generated by Django 5.2.5 on 2025-08-13 12:49

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_app', models.TextField()),
                ('slack_workspace_id', models.TextField(blank=True, null=True)),
                ('slack_workspace_bot_user_id', models.TextField(blank=True, null=True)),
                ('slack_workspace_bot_user_access_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
            ],
        ),
    ]
