# Generated by Django 5.2.5 on 2025-08-13 14:12

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('preferred_model', models.TextField(default='gpt-4o-mini')),
                ('max_completion_tokens', models.IntegerField(default=500)),
            ],
        ),
    ]
