# Generated by Django 5.2.5 on 2025-08-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_openaisettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(choices=[('SLACK', 'Slack'), ('TEAMS', 'Teams'), ('GOOGLE_CHAT', 'Google Chat'), ('ORBIT_ONE', 'Orbit One'), ('OTHER', 'Other')], default='SLACK')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('status', models.TextField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('ANSWERED', 'Answered')], default='OPEN')),
                ('top_data_sets', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('with_data_set', models.JSONField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_image_storage_file_path', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataquestion')),
            ],
        ),
    ]
